title: "Kumaran Baskaran"
description: "Structural Biology | Data Science | FAIR Data"
theme: jekyll-theme-cayman
repository: kumaranbaskaran/kumaranbaskaran.github.io
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
